In [1]:
import pandas as pd

In [2]:
# Read the Excel file
file_path = ("C:/Users/Saranya/Desktop/securecheck/Copy of traffic_stops.xlsx")
df = pd.read_excel(file_path)

In [3]:
# Display first few rows
df.head()

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305

In [4]:
display(df)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924

In [5]:
df.describe()

                           stop_date  driver_age_raw   driver_age
count                          65538    65538.000000  65538.00000
mean   2020-01-23 06:12:57.149134848       49.055998     49.11221
min              2020-01-01 00:00:00       18.000000     18.00000
25%              2020-01-12 00:00:00       33.000000     34.00000
50%              2020-01-23 00:00:00       49.000000     49.00000
75%              2020-02-04 00:00:00       65.000000     65.00000
max              2020-02-15 00:00:00       80.000000     80.00000
std                              NaN       18.174699     18.15012

In [ ]:
# checking Non-null values per column 
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  datetime64[ns]
 1   stop_time           65538 non-null  object
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         43818 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), datetime64[ns](1), int64(2), object(10)
memory usage: 6.7+ MB
None

In [ ]:
# total rows and columns
df.shape

(65538, 16)

In [8]:
# Check for missing values in each column
print(df.isnull().sum())

stop_date                 0
stop_time                 0
country_name              0
driver_gender             0
driver_age_raw            0
driver_age                0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
dtype: int64

In [9]:
# rows with any missing value	
df[df.isnull().any(axis=1)]

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
7,2020-01-01,00:07:00,India,M,72,50,Asian,Drunk Driving,Other,False,NaN,Arrest,True,30+ Min,True,DL75KZ7835
9,2020-01-01,00:09:00,USA,M,43,21,Asian,Signal Violation,Signal,True,NaN,Warning,True,16-30 Min,False,KA79RD2271
10,2020-01-01,00:10:00,India,F,66,76,Black,Speeding,Signal,False,NaN,Ticket,False,30+ Min,True,UP67CQ9426
13,2020-01-01,00:13:00,USA,M,55,58,Black,Seatbelt,DUI,False,NaN,Arrest,True,30+ Min,False,WB56XQ8946
14,2020-01-01,00:14:00,India,M,44,25,Black,Seatbelt,DUI,False,NaN,Arrest,True,30+ Min,False,GJ67CO6825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65523,2020-02-15,12:03:00,India,F,61,42,Other,Signal Violation,Other,True,NaN,Arrest,False,30+ Min,True,MH95JU7570
65529,2020-02-15,12:09:00,India,F,63,78,Black,Seatbelt,Seatbelt,True,NaN,Warning,False,0-15 Min,False,DL13IZ8119
65530,2020-02-15,12:10:00,India,M,34,72,White,Signal Violation,Seatbelt,True,NaN,Ticket,True,30+ Min,False,KA65MU9353
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924

In [10]:
# find and remove the missing values
df.dropna(axis=1, how='all', inplace=True)

In [ ]:
# replace NAN values
df.fillna({
    'search_type':'none'
}, inplace=True)

In [ ]:
# checking Nan is replaced with None
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,none,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,none,Ticket,True,16-30 Min,False,UP89PT2924

In [ ]:
#converting date and time from object to date & time
df['stop_date']=pd.to_datetime(df['stop_date'], format='%Y-%m-%d')
df['stop_time']=pd.to_datetime(df['stop_time'], format='%H:%M:%S')

In [15]:
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,1900-01-01 00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,1900-01-01 00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,1900-01-01 00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,1900-01-01 00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,1900-01-01 00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,1900-01-01 12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,1900-01-01 12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,1900-01-01 12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,1900-01-01 12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,none,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,1900-01-01 12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,none,Ticket,True,16-30 Min,False,UP89PT2924

In [ ]:
# Import PYMYSQL 
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\saranya\appdata\local\programs\python\python312\lib\site-packages (1.1.1)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# Inialize SQL Connection
import pymysql
# Connect to XAMPP MySQL
sp = pymysql.connect(
    host='localhost',
    user='root',
    password='',         
)

cursor = sp.cursor()
print("PyMySQL connection established!")

PyMySQL connection established!

In [24]:
# creating securecheck database 
cursor.execute("CREATE DATABASE SECURECHECK")

1

In [ ]:
# use database
cursor.execute("USE SECURECHECK")
sp.commit()

In [ ]:
# Table creation
cursor.execute("""CREATE TABLE SECURECHECK.logs (
id INT AUTO_INCREMENT PRIMARY KEY,
stop_date DATE,
stop_time TIME,
country_name VARCHAR(50),
driver_gender VARCHAR(10),
driver_age INT,
driver_race VARCHAR(50),
violation_raw VARCHAR(100),
violation VARCHAR(100),
search_conducted BOOLEAN,
search_type VARCHAR(100),
stop_outcome VARCHAR(100),
is_arrested BOOLEAN,
stop_duration VARCHAR(50),
drugs_related_stop BOOLEAN,
vehicle_number VARCHAR(50))
""")

0

In [27]:
sp.commit()
print("Table 'logs' created successfully in pymysql!")

Table 'logs' created successfully in pymysql!

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  datetime64[ns]
 1   stop_time           65538 non-null  datetime64[ns]
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         65538 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), datetime64[ns](2), int64(2), object(9)
memory usage: 6.7+ MB

In [ ]:
#insert police ledger data into SQL Table
for _, row in df.iterrows():
    cursor.execute("""
        INSERT INTO SECURECHECK.logs (
            stop_date, stop_time, country_name, driver_gender, driver_age,
            driver_race, violation_raw, violation, search_conducted, search_type,
            stop_outcome, is_arrested, stop_duration, drugs_related_stop, vehicle_number
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        row['stop_date'], row['stop_time'], row['country_name'], row['driver_gender'], row['driver_age'],
        row['driver_race'], row['violation_raw'], row['violation'], row['search_conducted'],
        row['search_type'], row['stop_outcome'], row['is_arrested'], row['stop_duration'],
        row['drugs_related_stop'], row['vehicle_number']
    ))

sp.commit()

In [30]:
cursor.close()
sp.close()

In [32]:
print("Data inserted into SECURECHECK.logs using iterrows()")

Data inserted into SECURECHECK.logs using iterrows()

In [33]:
# Check for missing values in each column
print(df.isnull().sum())

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
dtype: int64

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  datetime64[ns]
 1   stop_time           65538 non-null  datetime64[ns]
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         65538 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), datetime64[ns](2), int64(2), object(9)
memory usage: 6.7+ MB